//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Attributes will be private but in public properties</remarks>
/// <remarks>All Attributes starting with "d_" will have range of 1 to 100</remarks>
public class Person
{
	public virtual int d_LogicalOptimization
	{
		get;
		set;
	}

	public virtual int d_PhysicalOptimization
	{
		get;
		set;
	}

	public virtual int d_PrestigeGainRate
	{
		get;
		set;
	}

	public virtual int d_AbilityToPushAPIwithLessPrestige
	{
		get;
		set;
	}

	public virtual int d_TeamWork
	{
		get;
		set;
	}

	public virtual int d_Charisma
	{
		get;
		set;
	}

	public virtual int d_RDPointGainRate
	{
		get;
		set;
	}

	public virtual int d_EXPGainRate
	{
		get;
		set;
	}

	public virtual int d_ErrorCorrection
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

}

